# netlify.toml
[build]
  publish = "."
  functions = "netlify/functions"

# Redirect API requests to our serverless function
[[redirects]]
  from = "/api/together/*"
  to = "/.netlify/functions/together-proxy"
  status = 200

# Ensure all routes fallback to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
